import { NavBar } from "./components/general";

import { inter, mori } from "../lib/fonts";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${inter.variable} ${mori.variable}`} data-theme="dark">
            <body className='min-h-screen'>
                <NavBar/>
                {children}
            </body>
        </html>
    );
}
