import { SpeedInsights } from "@vercel/speed-insights/next";
import { inter, mori, neue } from "../lib/fonts";
import "./globals.css";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" className={`${inter.variable} ${mori.variable} ${neue.variable}`} data-theme="dark">
            <body className='min-h-screen bg-base-100'>
                {children}
                <SpeedInsights />
            </body>
        </html>
    );
}
